name: Update glossary

# Controls when the workflow will run
on:
  gollum:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      glossaryDefFile:
        required: true
        default: glossary.json
        description: glossaryDefFile
      deployBranch:
        required: false
        default: gh-pages
        description: This is where the output of script will be pushed to.
# explicitly configure permissions, in case your GITHUB_TOKEN workflow permissions are set to read-only in repository settings
permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.2

      - name: Install deps
        run: |
          git clone https://github.com/trustoverip/tt.git
          python -m pip install marko
          python -m pip install requests

      - name: Set variables
        env:
          DEFAULT_GLOSSARY_DEF_FILE: glossary.json
          DEFAULT_DEPLOY_BRANCH: gh-pages
        run: |
          echo "GLOSSARY_DEF_FILE=${{ github.event.inputs.glossaryDefFile || env.DEFAULT_GLOSSARY_DEF_FILE }}" >> $GITHUB_ENV
          echo "DEPLOY_BRANCH=${{ github.event.inputs.deployBranch || env.DEFAULT_DEPLOY_BRANCH }}" >> $GITHUB_ENV

      - name: Run script
        run: ./tt/bin/tt glossary ${{ env.GLOSSARY_DEF_FILE }} >glossary.html.new

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          # This token is required only if you have configured to store the signatures in a remote repository/organization
          PERSONAL_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          path-to-signatures: "signatures/version1/cla.json"
          path-to-document: "https://github.com/cla-assistant/github-action/blob/master/SAPCLA.md" # e.g. a CLA or a DCO document
          # branch should not be protected
          branch: "gh-pages"
          allowlist: user1,bot*

          # the followings are the optional inputs - If the optional inputs are not given, then default values will be taken
          #remote-organization-name: enter the remote organization name where the signatures should be stored (Default is storing the signatures in the same repository)
          #remote-repository-name: enter the  remote repository name where the signatures should be stored (Default is storing the signatures in the same repository)
          #create-file-commit-message: 'For example: Creating file for storing CLA Signatures'
          #signed-commit-message: 'For example: $contributorName has signed the CLA in $owner/$repo#$pullRequestNo'
          #custom-notsigned-prcomment: 'pull request comment with Introductory message to ask new contributors to sign'
          #custom-pr-sign-comment: 'The signature to be committed in order to sign the CLA'
          #custom-allsigned-prcomment: 'pull request comment when all contributors has signed, defaults to **CLA Assistant Lite bot** All Contributors have signed the CLA.'
          #lock-pullrequest-aftermerge: false - if you don't want this bot to automatically lock the pull request after merging (default - true)
          #use-dco-flag: true - If you are using DCO instead of CLA

      - name: Publishing
        run: |
          git fetch origin
          git checkout ${{ env.DEPLOY_BRANCH }}
          mv glossary.html.new glossary.html
          git add glossary.html
          git commit -m "auto-update glossary"
          git push
          echo DONE

      - name: Copy glossary.html to /static/ directory of the original branch
        run: |
          git fetch origin
          git checkout ${{ env.DEPLOY_BRANCH }}  # Switch back to the DEPLOY_BRANCH
          cp glossary.html ../glossary.html.temp  # Temporary copy
          git checkout $(echo ${{ github.ref }} | sed "s/refs\/heads\///g")  # Switch back to the original branch
          cp ../glossary.html.temp ./static/glossary.html  # Copy the existing glossary.html to the /static/ directory
          if [ $? -eq 0 ]; then
            echo "Successfully copied glossary.html to /static/ directory."
          else
            echo "Failed to copy glossary.html to /static/ directory."
            exit 1
          fi
          git add ./static/glossary.html
          git commit -m "Copy glossary.html to /static/ directory"
          git push